name: build_images

on:
  push:
  workflow_dispatch:

env:
  REF_NAME: ${{github.ref_name}}
  ROME_SDK_REF_NAME: main

permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout uniswap-v2-core repository'
        uses: actions/checkout@v4
        with:
          # path: uniswap-v2-core
          token: ${{ secrets.GIT_ROLLUP_TOKEN }}

      - name: 'Login to Docker Hub'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: 'Build uniswap-v2-core image'
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          push: true
          file: Dockerfile
          tags: romeprotocol/uniswap-v2-core:${{env.REF_NAME}}
          labels: romeprotocol/uniswap-v2-core:${{env.REF_NAME}}

      - name: 'Set latest tag'
        if: |
          ( ${{github.ref_name}} == 'main' )
        run: |
          
          docker pull romeprotocol/uniswap-v2-core:${REF_NAME}
          docker tag romeprotocol/uniswap-v2-core:${REF_NAME} romeprotocol/uniswap-v2-core:latest
          docker push romeprotocol/uniswap-v2-core:latest
